# Generated by Django 4.2.16 on 2025-04-02 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='compound',
            fields=[
                ('comp_id', models.AutoField(primary_key=True, serialize=False)),
                ('Fuel_type', models.CharField(blank=True, max_length=100, null=True)),
                ('zero_carbon_option', models.CharField(blank=True, max_length=100, null=True)),
                ('Fuel_type_rate', models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True)),
                ('Zero_carbon_rate', models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True)),
                ('green_premium_fuels', models.CharField(blank=True, max_length=100, null=True)),
                ('market', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('material_name', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='material_name')),
            ],
        ),
    ]
